version: '3.5'
name: 'organize-services'

services:
  database:
    image: 'postgres:latest'
    restart: always
    container_name: organize-database
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: password
      POSTGRES_DB: "organize"
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - '8010:5432'

volumes:
  database-data:
